"""first migration

Revision ID: 039f2cd949f7
Revises: 
Create Date: 2021-06-24 02:56:19.382284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039f2cd949f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('authorassociations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('developer_id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorassociations_id'), 'authorassociations', ['id'], unique=False)
    op.create_table('maintainerassociations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('developer_id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintainerassociations_id'), 'maintainerassociations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintainerassociations_id'), table_name='maintainerassociations')
    op.drop_table('maintainerassociations')
    op.drop_index(op.f('ix_authorassociations_id'), table_name='authorassociations')
    op.drop_table('authorassociations')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
