"""add in unique constraints

Revision ID: 396223e7d625
Revises: 039f2cd949f7
Create Date: 2021-06-24 03:04:15.207176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396223e7d625'
down_revision = '039f2cd949f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_developer_package_for_author_uc', 'authorassociations', ['developer_id', 'package_id'])
    op.create_unique_constraint(None, 'developers', ['name'])
    op.create_unique_constraint('_developer_package_for_maintainer_uc', 'maintainerassociations', ['developer_id', 'package_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_developer_package_for_maintainer_uc', 'maintainerassociations', type_='unique')
    op.drop_constraint(None, 'developers', type_='unique')
    op.drop_constraint('_developer_package_for_author_uc', 'authorassociations', type_='unique')
    # ### end Alembic commands ###
